create table if not exists public.gascars_place_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id uuid not null,
  place_id text not null,
  category text not null check (category in ('gas','mechanic','towing','parts')),
  event_type text not null check (event_type in ('impression','view','directions','call','website','service_request')),
  created_at timestamptz not null default now(),
  constraint gascars_place_events_place_id_length check (char_length(place_id) between 3 and 255)
);

alter table public.gascars_place_events enable row level security;

drop policy if exists "gascars admin place events select" on public.gascars_place_events;
create policy "gascars admin place events select"
on public.gascars_place_events
for select
to authenticated
using (public.gascars_is_admin());

revoke all on table public.gascars_place_events from anon, authenticated;
grant select on table public.gascars_place_events to authenticated;

create index if not exists gascars_place_events_created_idx
  on public.gascars_place_events(created_at desc);
create index if not exists gascars_place_events_place_idx
  on public.gascars_place_events(place_id, created_at desc);
create index if not exists gascars_place_events_kind_idx
  on public.gascars_place_events(event_type, created_at desc);

create or replace function public.gascars_places_quota_public(p_client_id uuid)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare
  today date := (now() at time zone 'UTC')::date;
  client_key text := 'public:' || p_client_id::text;
begin
  if p_client_id is null then raise exception 'Client identifier required'; end if;

  perform pg_advisory_xact_lock(hashtextextended('gascars-places-public-quota', 0));

  if coalesce((select count from gascars_private.places_usage where day=today and account='public-global'),0) >= 1500 then
    raise exception 'Daily search limit reached';
  end if;

  if coalesce((select count from gascars_private.places_usage where day=today and account=client_key),0) >= 80 then
    raise exception 'Daily client search limit reached';
  end if;

  insert into gascars_private.places_usage(day,account,count)
  values(today,'public-global',1),(today,client_key,1)
  on conflict(day,account)
  do update set count=gascars_private.places_usage.count+1;

  delete from gascars_private.places_usage where day<today-7;
end;
$$;

revoke all on function public.gascars_places_quota_public(uuid) from public, anon, authenticated;
grant execute on function public.gascars_places_quota_public(uuid) to service_role;

create or replace function public.gascars_track_place_events(
  p_user_id uuid,
  p_session_id uuid,
  p_place_ids text[],
  p_category text,
  p_event_type text
)
returns integer
language plpgsql
security definer
set search_path=''
as $$
declare
  safe_user_id uuid := null;
  inserted_count integer := 0;
begin
  if p_session_id is null then raise exception 'Session identifier required'; end if;
  if p_category not in ('gas','mechanic','towing','parts') then raise exception 'Invalid category'; end if;
  if p_event_type not in ('impression','view','directions','call','website','service_request') then raise exception 'Invalid event type'; end if;
  if coalesce(array_length(p_place_ids,1),0) < 1 or array_length(p_place_ids,1) > 25 then raise exception 'Invalid place list'; end if;

  if p_user_id is not null and exists(select 1 from auth.users where id=p_user_id) then
    safe_user_id := p_user_id;
  end if;

  insert into public.gascars_place_events(user_id,session_id,place_id,category,event_type)
  select safe_user_id,p_session_id,btrim(place_id),p_category,p_event_type
  from unnest(p_place_ids) as place_id
  where char_length(btrim(place_id)) between 3 and 255;

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

revoke all on function public.gascars_track_place_events(uuid,uuid,text[],text,text) from public, anon, authenticated;
grant execute on function public.gascars_track_place_events(uuid,uuid,text[],text,text) to service_role;

create or replace function public.gascars_admin_dashboard()
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $$
begin
  if not public.gascars_is_admin() then raise exception 'Admin access required'; end if;
  return jsonb_build_object(
    'users',(select count(*) from public.gascars_profiles),
    'businesses',(select count(*) from public.gascars_businesses),
    'pending_businesses',(select count(*) from public.gascars_businesses where status='pending'),
    'active_businesses',(select count(*) from public.gascars_businesses where status='active'),
    'open_leads',(select count(*) from public.gascars_leads where status='open'),
    'completed_leads',(select count(*) from public.gascars_leads where status='completed'),
    'services',(select count(*) from public.gascars_services where active),
    'open_support_tickets',(select count(*) from public.gascars_support_tickets where status='open'),
    'unlocks',(select count(*) from public.gascars_lead_unlocks where status='unlocked'),
    'credits_outstanding',(select coalesce(sum(balance),0) from public.gascars_wallets),
    'place_impressions_30d',(select count(*) from public.gascars_place_events where event_type='impression' and created_at >= now() - interval '30 days'),
    'place_views_30d',(select count(*) from public.gascars_place_events where event_type='view' and created_at >= now() - interval '30 days'),
    'place_directions_30d',(select count(*) from public.gascars_place_events where event_type='directions' and created_at >= now() - interval '30 days'),
    'place_calls_30d',(select count(*) from public.gascars_place_events where event_type='call' and created_at >= now() - interval '30 days'),
    'place_websites_30d',(select count(*) from public.gascars_place_events where event_type='website' and created_at >= now() - interval '30 days'),
    'place_service_requests_30d',(select count(*) from public.gascars_place_events where event_type='service_request' and created_at >= now() - interval '30 days'),
    'place_unique_30d',(select count(distinct place_id) from public.gascars_place_events where created_at >= now() - interval '30 days')
  );
end;
$$;
