insert into public.gascars_services
  (slug,name,category,group_name,description,keywords,sort_order,active)
values
  ('abs-brake-system','ABS brake system diagnosis','repair','Brakes','Diagnosis and repair for ABS lights, wheel-speed sensors and anti-lock braking faults.',array['abs','anti lock','brake light','wheel speed sensor','traction light'],13,true),
  ('brake-caliper-service','Brake caliper repair / replacement','repair','Brakes','Repair sticking, leaking or damaged brake calipers.',array['caliper','brake caliper','sticking brake','pulling when braking'],14,true),
  ('brake-fluid-service','Brake fluid leak / flush','repair','Brakes','Brake-fluid leaks, contaminated fluid and hydraulic brake service.',array['brake fluid','soft pedal','spongy brakes','hydraulic','brake leak'],15,true),
  ('parking-brake-repair','Parking brake repair','repair','Brakes','Parking brake, emergency brake and electronic parking brake faults.',array['parking brake','emergency brake','e brake','ebrake','electronic parking brake'],16,true),
  ('engine-no-start','Engine will not start diagnosis','repair','Engine','Diagnosis when the engine will not start or only clicks/cranks.',array['wont start','will not start','no start','not starting','clicking','cranks but wont start','car wont start'],53,true),
  ('engine-misfire','Engine misfire / rough running','repair','Engine','Diagnosis for shaking, misfires, rough idle and uneven engine operation.',array['misfire','rough idle','shaking engine','runs rough','engine shaking','jerking'],54,true),
  ('engine-overheating','Engine overheating diagnosis','repair','Cooling','Diagnosis for overheating, high temperature or repeated coolant loss.',array['overheating','overheat','hot engine','temperature high','temp gauge','coolant'],55,true),
  ('engine-stalling','Engine stalling / shuts off','repair','Engine','Diagnosis when the engine stalls, dies or shuts off while driving or idling.',array['stall','stalling','dies','shuts off','engine turns off','cuts out'],56,true),
  ('engine-power-loss','Loss of power / poor acceleration','repair','Engine','Diagnosis for weak acceleration, hesitation and reduced engine power.',array['loss of power','no power','slow acceleration','hesitation','bogging','weak acceleration'],57,true),
  ('engine-oil-leak','Engine oil leak diagnosis','repair','Engine','Locate and repair engine oil leaks.',array['oil leak','leaking oil','oil on ground','engine leak'],58,true),
  ('engine-noise','Engine noise diagnosis','repair','Engine','Diagnosis for knocking, ticking, rattling or unusual engine noises.',array['knocking','ticking','rattle','rattling','engine noise','motor noise','clunk'],59,true),
  ('engine-smoke','Engine smoke diagnosis','repair','Engine','Diagnosis for blue, white or black exhaust smoke.',array['smoke','blue smoke','white smoke','black smoke','smoking engine'],60,true),
  ('spark-plug-ignition','Spark plugs / ignition coils','repair','Engine','Spark plug, ignition coil and ignition-system service.',array['spark plug','spark plugs','coil','ignition coil','tune up','misfire'],61,true),
  ('timing-belt-chain','Timing belt / timing chain','repair','Engine','Timing belt, timing chain, tensioner and related timing service.',array['timing belt','timing chain','tensioner','timing noise'],62,true),
  ('head-gasket-repair','Head gasket diagnosis / repair','repair','Engine','Diagnosis and repair for suspected head-gasket failure.',array['head gasket','coolant in oil','white smoke','overheating','milky oil'],63,true),
  ('engine-compression','Engine compression / internal diagnosis','repair','Engine','Compression, leak-down and internal engine diagnosis.',array['compression','low compression','leak down','internal engine'],64,true),
  ('radiator-repair','Radiator repair / replacement','repair','Cooling','Radiator leak, blockage or cooling-performance repair.',array['radiator','radiator leak','coolant leak','cooling system'],65,true),
  ('water-pump-repair','Water pump replacement','repair','Cooling','Water-pump leaks, bearing noise and coolant-circulation faults.',array['water pump','coolant pump','waterpump','coolant leak'],66,true),
  ('thermostat-repair','Thermostat replacement','repair','Cooling','Thermostat faults causing overheating or slow warm-up.',array['thermostat','overheating','runs cold','temperature'],67,true),
  ('coolant-leak','Coolant leak diagnosis','repair','Cooling','Locate coolant or antifreeze leaks from hoses, radiator, reservoir or engine.',array['coolant leak','antifreeze leak','coolant low','green fluid','pink fluid'],68,true),
  ('cooling-fan-repair','Cooling fan repair','repair','Cooling','Radiator fan, relay and fan-control diagnosis.',array['cooling fan','radiator fan','fan not working','overheating in traffic'],69,true),
  ('fuse-relay-diagnosis','Fuse / relay electrical diagnosis','repair','Electrical','Electrical faults caused by blown fuses, relays or power distribution.',array['fuse','relay','electrical','no power','blown fuse'],33,true),
  ('wiring-electrical','Wiring / electrical fault diagnosis','repair','Electrical','Diagnosis of wiring, grounds, shorts and intermittent electrical problems.',array['wiring','wire','short circuit','ground','electrical problem','intermittent'],34,true),
  ('exterior-light-repair','Headlight / brake light / signal repair','repair','Electrical','Repair exterior lighting, turn signals and brake lights.',array['headlight','brake light','tail light','turn signal','blinker','light not working'],35,true),
  ('power-window-repair','Power window repair','repair','Electrical','Window motor, regulator, switch and wiring repair.',array['window','power window','window wont go up','window stuck','window regulator'],36,true),
  ('power-lock-repair','Power door lock repair','repair','Electrical','Power lock actuator, switch and wiring repair.',array['door lock','power lock','lock actuator','door wont lock'],37,true),
  ('wiper-washer-repair','Wiper / washer repair','repair','Electrical','Windshield wiper motor, linkage, blades and washer-system diagnosis.',array['wiper','wipers','washer','windshield washer','wiper motor'],38,true),
  ('horn-repair','Horn repair','repair','Electrical','Horn, relay, switch and clock-spring diagnosis.',array['horn','horn not working','beep'],39,true),
  ('fuel-pump-repair','Fuel pump diagnosis / replacement','repair','Fuel & Air','Fuel-pump, fuel-pressure and delivery-system diagnosis.',array['fuel pump','gas pump','fuel pressure','wont start','loses power'],81,true),
  ('fuel-injector-service','Fuel injector service / repair','repair','Fuel & Air','Injector cleaning, diagnosis and replacement.',array['injector','fuel injector','injectors','misfire','fuel smell'],82,true),
  ('throttle-body-service','Throttle body / idle control service','repair','Fuel & Air','Throttle-body, idle and electronic throttle diagnosis.',array['throttle body','idle','high idle','low idle','electronic throttle','stalls'],83,true),
  ('maf-map-sensor','MAF / MAP sensor diagnosis','repair','Fuel & Air','Airflow and manifold-pressure sensor diagnosis.',array['maf','map sensor','mass air flow','airflow sensor','hesitation'],84,true),
  ('intake-vacuum-leak','Vacuum / intake leak diagnosis','repair','Fuel & Air','Locate intake, vacuum and unmetered-air leaks.',array['vacuum leak','intake leak','hissing','lean code','rough idle'],85,true),
  ('exhaust-repair','Exhaust leak / muffler repair','repair','Exhaust','Exhaust pipe, muffler, resonator and exhaust-leak repair.',array['exhaust','muffler','loud exhaust','exhaust leak','rattle'],86,true),
  ('catalytic-converter','Catalytic converter diagnosis / replacement','repair','Exhaust','Catalytic-converter efficiency, restriction and replacement service.',array['catalytic converter','cat converter','p0420','emissions','rotten egg smell'],87,true),
  ('oxygen-sensor','Oxygen sensor replacement','repair','Exhaust','O2 sensor and air-fuel sensor diagnosis.',array['oxygen sensor','o2 sensor','air fuel sensor','check engine'],88,true),
  ('emissions-repair','Emissions / inspection failure diagnosis','repair','Exhaust','Diagnosis after emissions or inspection failure.',array['emissions','smog','inspection failed','emission test','evap'],89,true),
  ('transmission-fluid-service','Transmission fluid service','repair','Transmission','Transmission fluid and filter service.',array['transmission fluid','gear oil','trans service','fluid change'],90,true),
  ('transmission-shifting','Transmission shifting problem diagnosis','repair','Transmission','Diagnosis for slipping, hard shifts, delayed engagement or gear faults.',array['slipping','hard shift','wont shift','transmission slipping','gear problem','jerking transmission'],91,true),
  ('clutch-repair','Clutch repair / replacement','repair','Drivetrain','Manual-transmission clutch diagnosis and replacement.',array['clutch','clutch slipping','manual transmission','clutch pedal'],92,true),
  ('cv-axle-repair','CV axle / CV joint repair','repair','Drivetrain','CV axle, joint and boot diagnosis and replacement.',array['cv axle','cv joint','clicking turn','axle','cv boot'],93,true),
  ('wheel-bearing-repair','Wheel bearing / hub repair','repair','Drivetrain','Wheel-bearing and hub diagnosis for humming, grinding or looseness.',array['wheel bearing','hub bearing','humming','wheel noise','bearing'],94,true),
  ('differential-service','Differential service / repair','repair','Drivetrain','Front or rear differential fluid, noise and leak repair.',array['differential','diff','gear oil','rear end noise','differential leak'],95,true),
  ('driveshaft-repair','Driveshaft / U-joint repair','repair','Drivetrain','Driveshaft, U-joint and vibration diagnosis.',array['driveshaft','drive shaft','u joint','universal joint','vibration'],96,true),
  ('transfer-case-repair','Transfer case / 4WD repair','repair','Drivetrain','Transfer-case and four-wheel-drive system diagnosis.',array['transfer case','4wd','four wheel drive','awd','4x4'],97,true),
  ('shock-strut-service','Shocks / struts replacement','repair','Suspension','Shock absorber and strut diagnosis and replacement.',array['shock','shocks','strut','struts','bouncy ride','suspension'],98,true),
  ('ball-joint-tie-rod','Ball joint / tie rod repair','repair','Suspension','Steering and suspension joint diagnosis and replacement.',array['ball joint','tie rod','steering loose','clunk suspension'],99,true),
  ('power-steering-repair','Power steering diagnosis / repair','repair','Suspension','Hydraulic or electric power-steering fault diagnosis.',array['power steering','hard steering','steering heavy','steering light','eps'],100,true),
  ('vehicle-vibration','Vehicle shaking / vibration diagnosis','repair','Diagnostics','Diagnosis for vibration through the wheel, seat or body while driving.',array['vibration','shaking','car shakes','steering wheel shakes','vibrates'],101,true),
  ('pulling-wandering','Vehicle pulls / wanders diagnosis','repair','Suspension','Diagnosis when the vehicle pulls, wanders or feels unstable.',array['pulling','pulls left','pulls right','wanders','unstable steering'],102,true),
  ('wheel-balance','Wheel / tire balancing','repair','Tires','Wheel balancing for highway-speed vibration and uneven ride.',array['balance','wheel balance','tire balance','vibration highway'],103,true),
  ('wheel-rim-repair','Bent wheel / rim repair','repair','Tires','Diagnosis or repair for bent, cracked or damaged wheels.',array['rim','wheel','bent rim','cracked wheel','wheel damage'],104,true),
  ('tpms-service','TPMS / tire pressure sensor service','repair','Tires','Tire-pressure monitoring sensor diagnosis and replacement.',array['tpms','tire pressure light','pressure sensor','tire sensor'],105,true),
  ('heater-repair','Heater diagnosis / repair','repair','Climate','Cabin heater, heater core and temperature-control diagnosis.',array['heater','no heat','heater core','cold cabin'],106,true),
  ('blower-motor-repair','Blower motor / fan repair','repair','Climate','Cabin blower motor, resistor and fan-speed diagnosis.',array['blower','blower motor','fan not blowing','ac fan','heater fan'],107,true),
  ('belt-hose-service','Belts / hoses inspection & replacement','repair','Maintenance','Accessory belts, serpentine belt and engine-hose service.',array['serpentine belt','belt','hose','hoses','squealing belt'],108,true),
  ('air-filter-service','Engine air filter replacement','repair','Maintenance','Engine air-filter inspection and replacement.',array['air filter','engine filter','dirty filter'],109,true),
  ('cabin-filter-service','Cabin air filter replacement','repair','Maintenance','Cabin/pollen filter replacement.',array['cabin filter','pollen filter','ac smell','weak air'],115,true),
  ('coolant-flush','Coolant / antifreeze service','repair','Maintenance','Cooling-system fluid replacement and flush.',array['coolant flush','antifreeze','coolant service','radiator flush'],116,true),
  ('transmission-maintenance','Scheduled transmission maintenance','repair','Maintenance','Preventive automatic or manual transmission maintenance.',array['transmission maintenance','transmission service','scheduled service'],117,true),
  ('prepurchase-inspection','Pre-purchase vehicle inspection','repair','Inspection','Mechanical inspection before buying a used vehicle.',array['pre purchase','prepurchase','used car inspection','before buying','ppi'],118,true),
  ('road-trip-inspection','Road-trip / safety inspection','repair','Inspection','General safety and reliability inspection before travel.',array['road trip','trip inspection','safety inspection','vehicle inspection'],119,true),
  ('airbag-srs-diagnosis','Airbag / SRS warning diagnosis','repair','Safety','Airbag, SRS, seat-belt pretensioner and restraint-system diagnosis.',array['airbag','srs','airbag light','restraint system','seat belt light'],120,true),
  ('backup-camera-sensor','Backup camera / parking sensor repair','repair','Safety','Backup camera, parking sensor and related driver-assistance repair.',array['backup camera','rear camera','parking sensor','reverse camera','sensor'],121,true),
  ('adas-warning-diagnosis','ADAS / driver-assistance warning diagnosis','repair','Safety','Lane, collision, radar or camera system warning diagnosis.',array['adas','lane assist','collision warning','radar','camera calibration'],122,true),
  ('door-latch-repair','Door / latch repair','repair','Body & Comfort','Door latch, handle and closing/locking mechanism repair.',array['door','door latch','door handle','door wont close','door stuck'],123,true),
  ('mirror-repair','Side mirror repair / replacement','repair','Body & Comfort','Power or manual exterior mirror repair.',array['mirror','side mirror','power mirror','broken mirror'],124,true),
  ('sunroof-repair','Sunroof / moonroof repair','repair','Body & Comfort','Sunroof motor, track, drain or leak repair.',array['sunroof','moonroof','roof leak','sunroof stuck'],125,true),
  ('strange-noise-diagnosis','Strange noise diagnosis','repair','Diagnostics','General diagnosis for a noise when the source is unknown.',array['noise','strange noise','clunk','rattle','squeak','hum','whine','grind'],126,true),
  ('fluid-leak-diagnosis','Unknown fluid leak diagnosis','repair','Diagnostics','Identify and diagnose an unknown automotive fluid leak.',array['fluid leak','leak','puddle','dripping','liquid under car'],127,true),
  ('warning-light-diagnosis','Dashboard warning light diagnosis','repair','Diagnostics','Diagnosis for dashboard warning lights when the exact system is unknown.',array['warning light','dash light','dashboard light','service light','light on dash'],128,true),
  ('burning-smell-diagnosis','Burning smell / unusual odor diagnosis','repair','Diagnostics','Diagnosis for burning, fuel, coolant or electrical smells.',array['burning smell','smell','odor','gas smell','fuel smell','electrical smell'],129,true),
  ('other-repair','Other / I am not sure what is wrong','repair','Other','Choose this when the problem is not listed or you are not sure what service is needed.',array['other','something else','not sure','unknown problem','dont know','diagnose','general diagnosis'],199,true),
  ('winch-out-recovery','Winch-out / stuck vehicle recovery','towing','Roadside','Recovery when a vehicle is stuck in mud, sand, snow, ditch or soft ground.',array['winch','stuck','ditch','mud','snow','sand','recovery'],115,true),
  ('accident-recovery','Accident / collision towing','towing','Roadside','Tow or recovery after a crash or collision.',array['accident','crash','collision','wreck','recovery tow'],116,true),
  ('motorcycle-towing','Motorcycle towing','towing','Roadside','Transport for motorcycles and scooters.',array['motorcycle','bike tow','motorbike','scooter'],117,true),
  ('long-distance-towing','Long-distance vehicle towing','towing','Roadside','Longer-distance towing to a selected destination.',array['long distance tow','long tow','transport vehicle','far tow'],118,true),
  ('roadside-battery-replacement','Roadside battery replacement','towing','Roadside','Mobile battery testing and replacement when supported by the provider.',array['battery replacement','dead battery','roadside battery','mobile battery'],119,true),
  ('other-roadside','Other roadside help','towing','Other','Choose this for a roadside problem that is not listed.',array['other','roadside','something else','not listed','unknown roadside'],199,true)
on conflict (slug) do update
set name=excluded.name,
    category=excluded.category,
    group_name=excluded.group_name,
    description=excluded.description,
    keywords=excluded.keywords,
    sort_order=excluded.sort_order,
    active=excluded.active;
